version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    environment:
      - PORT=${PORT}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
    ports:
      - '80:3000'
    volumes:
      - ./src:/app/src
